### ISSUE TITLE
Error on install flintcms

### ISSUE THREAD

**Issue by devtechk** [JasonEtco/flintcms#76]
Hello Guys, 
I've installed flint following https://flintcms.co/docs/installation/ but once i run node index.js somre errors displays:

(node:20789) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
    at missingEnvVariables.forEach.v (/home/antonio/Scrivania/experiments/flintpractice/node_modules/flintcms/server/utils/validate-env-variables.js:14:40)
    at Array.forEach (<anonymous>)
    at validateEnvVariables (/home/antonio/Scrivania/experiments/flintpractice/node_modules/flintcms/server/utils/validate-env-variables.js:14:23)
    at Flint.startServer (/home/antonio/Scrivania/experiments/flintpractice/node_modules/flintcms/index.js:93:33)
    at Object.<anonymous> (/home/antonio/Scrivania/experiments/flintpractice/index.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
(node:20789) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20789) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
I'm the only who get this error?
Thanks

**Comment by banChakri** [comment]
Same here, is there any configuration we are missing..

**Comment by RussMorg-SMSDev** [comment]
I also encountered the same issue, didnt want to just respond saying that...But I would love for this to get some attention, as I am/was interested in utilizing it for a project and several others going forward...

**Comment by rkgttr** [comment]
Same issue, the issue has been lodged last summer and no answer. Is this project dead?

**Comment by JasonEtco** [comment]
This is being caused by one of two missing environment variables, `DB_HOST` or `SESSION_SECRET`. I'll release a new version with #78.

And @rkgttr, just a heads up - asking if a project is dead is kinda rude. It puts pressure on the maintainer to fix your problems, because no one _wants_ their projects to die - despite not having time to maintain it.

**Comment by rkgttr** [comment]
Sorry @JasonEtco , didn't mean to be rude at all. I myself have a couple projects for which I don't have a lot of time so totally understand :)
Thanks for the fix.
